name: ohana_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.0.0
  get: ^4.6.6
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  firebase_storage_web: ^3.9.9
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.11
  go_router: ^14.1.4
  quill_html_editor: ^2.2.8
  firebase_auth: ^5.1.1
  url_launcher: ^6.3.0
  diacritic: ^0.1.5
  
dependency_overrides:
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
