name: ohana_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  file_picker: ^6.2.1
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.11
  go_router: ^14.1.4
  image_picker: ^1.1.2
  intl: ^0.18.1
  quill_html_editor: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
