// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCep9UEzAI2d9hUtdtDjbjbXIC8ih2Nm6w',
    appId: '1:592154909664:web:e57764dee245756683a985',
    messagingSenderId: '592154909664',
    projectId: 'ohana-383fe',
    authDomain: 'ohana-383fe.firebaseapp.com',
    storageBucket: 'ohana-383fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIVacpB6vEWgj7zBEDYrKrHjq8ufMpKU',
    appId: '1:592154909664:android:3529a0c921cd4b2e83a985',
    messagingSenderId: '592154909664',
    projectId: 'ohana-383fe',
    storageBucket: 'ohana-383fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOR1nv15GaXZACUd634BU6JvyQcY7pVE',
    appId: '1:592154909664:ios:4ca4fa8869b048fc83a985',
    messagingSenderId: '592154909664',
    projectId: 'ohana-383fe',
    storageBucket: 'ohana-383fe.appspot.com',
    iosBundleId: 'com.example.ohanaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByOR1nv15GaXZACUd634BU6JvyQcY7pVE',
    appId: '1:592154909664:ios:4ca4fa8869b048fc83a985',
    messagingSenderId: '592154909664',
    projectId: 'ohana-383fe',
    storageBucket: 'ohana-383fe.appspot.com',
    iosBundleId: 'com.example.ohanaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCep9UEzAI2d9hUtdtDjbjbXIC8ih2Nm6w',
    appId: '1:592154909664:web:d7d2bc4d44ca706083a985',
    messagingSenderId: '592154909664',
    projectId: 'ohana-383fe',
    authDomain: 'ohana-383fe.firebaseapp.com',
    storageBucket: 'ohana-383fe.appspot.com',
  );

}